"""Minimal standalone JWKS/discovery test double (demo-readiness.md §2/§3/Decision 2).

Stands in for Entra's own always-public discovery/JWKS endpoints, plus a `/mint` route
that signs a JWT shaped exactly like a real Entra v2.0 access token (iss, aud, exp, nbf,
iat, sub, oid, roles). Used *only* by scripts/seed.sh and scripts/verify-seed.sh
(host-side, never by the frontend/MSAL, never part of scripts/cold-start.sh) so those
scripts can drive the real bookings/BFF API without ROPC against the real tenant.

Review iteration 2, finding 1: the RSA key pair is now persisted to MOCK_JWKS_KEY_PATH
(a Docker-managed named volume scoped to infra/testing/compose.yml only, never a bind
mount, never checked into git, never part of any real-environment config) so the key -
and therefore the JWKS response under its fixed `kid` - stays identical across this
container's own restarts. Without this, a second scripts/seed-demo-data.sh invocation
against an app stack still warm from a first invocation would mint tokens under a
freshly-regenerated key while bff/catalog/bookings still served requests against the
first instance's cached JWKS for the same `kid`, failing every signature check. It is
still generated by this process (never supplied from outside), still a throwaway
keypair with no real-environment blast radius (§7 A02) - a leaked private key from this
test double could at most mint a token that real, Entra-configured services (which never
point their OIDC_ISSUER_URI here) would reject outright on issuer mismatch.
"""

import base64
import os
import time

import jwt as pyjwt
from cryptography.hazmat.primitives.asymmetric import rsa
from cryptography.hazmat.primitives import serialization
from flask import Flask, jsonify, request

ISSUER = os.environ.get("MOCK_JWKS_ISSUER", "http://mock-jwks:1080/mock-tenant/v2.0")
AUDIENCE = os.environ.get("MOCK_JWKS_AUDIENCE", "api://mock-audience")
KEY_ID = "mock-jwks-key-1"
ALLOWED_ROLES = {"ADMIN", "TECNICO", "ESTUDIANTE", "AUDITOR"}
TOKEN_LIFETIME_SECONDS = 3600
KEY_PATH = os.environ.get("MOCK_JWKS_KEY_PATH", "/keys/private_key.pem")


def _load_or_generate_private_key() -> rsa.RSAPrivateKey:
    # Review iteration 2, finding 1: reuse the persisted key across this container's own
    # restarts so the kid this instance serves always corresponds to the same key another,
    # already-running service's cached JWKS response may still be holding.
    if os.path.exists(KEY_PATH):
        with open(KEY_PATH, "rb") as key_file:
            return serialization.load_pem_private_key(key_file.read(), password=None)

    key = rsa.generate_private_key(public_exponent=65537, key_size=2048)
    pem = key.private_bytes(
        encoding=serialization.Encoding.PEM,
        format=serialization.PrivateFormat.PKCS8,
        encryption_algorithm=serialization.NoEncryption(),
    )
    os.makedirs(os.path.dirname(KEY_PATH), exist_ok=True)
    with open(KEY_PATH, "wb") as key_file:
        key_file.write(pem)
    os.chmod(KEY_PATH, 0o600)
    return key


_private_key = _load_or_generate_private_key()
_private_pem = _private_key.private_bytes(
    encoding=serialization.Encoding.PEM,
    format=serialization.PrivateFormat.PKCS8,
    encryption_algorithm=serialization.NoEncryption(),
)


def _b64url_uint(value: int) -> str:
    raw = value.to_bytes((value.bit_length() + 7) // 8, "big")
    return base64.urlsafe_b64encode(raw).rstrip(b"=").decode("ascii")


_public_numbers = _private_key.public_key().public_numbers()
_jwk = {
    "kty": "RSA",
    "use": "sig",
    "alg": "RS256",
    "kid": KEY_ID,
    "n": _b64url_uint(_public_numbers.n),
    "e": _b64url_uint(_public_numbers.e),
}

app = Flask(__name__)


@app.get("/mock-tenant/v2.0/.well-known/openid-configuration")
def openid_configuration():
    return jsonify({"issuer": ISSUER, "jwks_uri": f"{ISSUER}/discovery/v2.0/keys"})


@app.get("/mock-tenant/v2.0/discovery/v2.0/keys")
def jwks():
    return jsonify({"keys": [_jwk]})


@app.post("/mock-tenant/v2.0/mint")
def mint():
    # A08: the only thing ever deserialized here is this request's own body, into two
    # plain strings validated against a fixed allow-list - never reflectively bound,
    # never used to build a path/SQL string/shell command.
    body = request.get_json(silent=True) or {}
    role = body.get("role")
    oid = body.get("oid")
    if role not in ALLOWED_ROLES:
        return jsonify({"error": f"role must be one of {sorted(ALLOWED_ROLES)}"}), 400
    if not oid or not isinstance(oid, str):
        return jsonify({"error": "oid is required and must be a non-empty string"}), 400

    now = int(time.time())
    claims = {
        "iss": ISSUER,
        "aud": AUDIENCE,
        "sub": oid,
        "oid": oid,
        "roles": [role],
        "iat": now,
        "nbf": now - 5,
        "exp": now + TOKEN_LIFETIME_SECONDS,
    }
    token = pyjwt.encode(claims, _private_pem, algorithm="RS256", headers={"kid": KEY_ID})
    # A09: never log the token itself, only that one was minted and for whom.
    print(f"mock-jwks: outcome=[MINTED] role=[{role}] oid=[{oid}]", flush=True)
    return jsonify({"token": token})


@app.get("/healthz")
def healthz():
    return jsonify({"status": "UP"})


if __name__ == "__main__":
    port = int(os.environ.get("MOCK_JWKS_PORT", "1080"))
    app.run(host="0.0.0.0", port=port)
