spring:
  application:
    name: ms-campuslab-kafka-admin
server:
  port: ${SERVER_PORT:8080}
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: never

oidc:
  issuer-uri: ${OIDC_ISSUER_URI}
  audience: ${OIDC_AUDIENCE}

kafka:
  bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
  topic:
    replication-factor: ${KAFKA_TOPIC_REPLICATION_FACTOR:1}
